Smaller changes.

diff --git a/.github/workflows/updateOpenStack.yml b/.github/workflows/updateOpenStack.yml
--- a/.github/workflows/updateOpenStack.yml
+++ b/.github/workflows/updateOpenStack.yml
@@ -71,32 +71,35 @@ jobs:
           sudo apt install -y python3-openstackclient
           pip install python-heatclient
 
+      - name: Install Netcat
+        run: sudo apt install -y netcat
+
       - name: Authenticate with OpenStack
         run: echo "Authenticated with OpenStack"
 
       - name: Instance Status Check
         run: |
-          openstack server list | grep "ACTIVE" || exit 1
+          openstack server list | grep "ACTIVE" || (echo "Instance status check failed" && exit 1)
 
       - name: Resource Limits Test
         run: |
-          openstack server show Portfolio-Ubuntu-Instance -f json | jq '.flavor' | grep "gx3.2c3r" || exit 1
+          openstack server show Portfolio-Ubuntu-Instance -f json | jq '.flavor' | grep "gx3.2c3r" || (echo "Resource limits check failed" && exit 1)
 
       - name: Connectivity Test with curl
         run: |
-          curl -s -I http://10.212.27.244 || exit 1
+          curl -s -I http://10.212.27.244 || (echo "Connectivity test failed" && exit 1)
 
       - name: Security Group Test
         run: |
-          openstack security group rule list 3a02cd53-6770-4f12-a5a5-6d5d2393a8f6 || exit 1
+          openstack security group rule list 3a02cd53-6770-4f12-a5a5-6d5d2393a8f6 || (echo "Security group test failed" && exit 1)
 
-      #- name: Port Test
-      #  run: |
-      #    nc -zv 10.212.27.244 22 && echo "Port 22 open" || exit 1
+      - name: Port Test
+        run: |
+          nc -zv 10.212.27.244 22 && echo "Port 22 open" || (echo "Port 22 is not open" && exit 1)
 
       - name: Service Availability Check
         run: |
-          curl -I http://10.212.27.244 || exit 1
+          curl -I http://10.212.27.244 || (echo "Service availability check failed" && exit 1)
 
   deploy-hello-world:
     runs-on: ubuntu-latest
